local L = LibStub("AceLocale-3.0"):NewLocale("HudMap", "koKR")
if not L then return end

L["Bastion of Twilight"] = "황혼의 성채"
L["Beth'tilac"] = "베스틸락"
L["Blackwing Descent"] = "검은날개 강림지"
L["Caustic Slime Range"] = "부식성 진흙 거리"
L["Chimaeron"] = "키마이론"
L["Cho'Gall"] = "초갈"
L["Crystal Trap Duration"] = "수정 감옥 덫 지속시간"
L["Firelands"] = "불의땅"
L["Immolation Trap Duration"] = "제물의 덪 지속시간"
L["Majordomo Staghelm"] = "청지기 스태그헬름"
L["Maloriak"] = "말로리악"
L["Omnotron Defense System"] = "만능골렘 방어 시스템"
L["Shannox"] = "샤녹스"
L["Sinestra"] = "시네스트라"
L["Twilight Ascendant Council"] = "승천 의회"
L["Valiona and Theralion"] = "발리오나와 테랄리온"
L["Worship Radius"] = "개종 반경"
L["Wrack"] = "파멸"
L["Wrack End"] = "파멸 끝"
L["Wrack Radius"] = "파멸 반경"
L["Wrack Start"] = "파멸 시작"
