local L = LibStub("AceLocale-3.0"):NewLocale("HudMap", "zhCN")
if not L then return end

L["Bastion of Twilight"] = "暮光堡垒"
-- L["Beth'tilac"] = ""
L["Blackwing Descent"] = "黑翼血环"
L["Caustic Slime Range"] = "腐蚀烂泥范围"
L["Chimaeron"] = "奇美隆"
L["Cho'Gall"] = "古加尔"
-- L["Crystal Trap Duration"] = ""
-- L["Firelands"] = ""
-- L["Immolation Trap Duration"] = ""
-- L["Majordomo Staghelm"] = ""
L["Maloriak"] = "马洛拉克"
L["Omnotron Defense System"] = "全能金刚防御系统"
-- L["Shannox"] = ""
L["Sinestra"] = "希奈丝特拉"
L["Twilight Ascendant Council"] = "升腾者议会"
L["Valiona and Theralion"] = "瓦里昂娜和瑟纳利昂"
L["Worship Radius"] = "膜拜半径"
L["Wrack"] = "毁灭"
L["Wrack End"] = "毁灭结束"
L["Wrack Radius"] = "毁灭半径"
L["Wrack Start"] = "毁灭开始"
