local L = LibStub("AceLocale-3.0"):NewLocale("HudMap", "esMX")
if not L then return end

-- L["Bastion of Twilight"] = ""
-- L["Beth'tilac"] = ""
-- L["Blackwing Descent"] = ""
-- L["Caustic Slime Range"] = ""
-- L["Chimaeron"] = ""
-- L["Cho'Gall"] = ""
-- L["Crystal Trap Duration"] = ""
-- L["Firelands"] = ""
-- L["Immolation Trap Duration"] = ""
-- L["Majordomo Staghelm"] = ""
-- L["Maloriak"] = ""
-- L["Omnotron Defense System"] = ""
-- L["Shannox"] = ""
-- L["Sinestra"] = ""
-- L["Twilight Ascendant Council"] = ""
-- L["Valiona and Theralion"] = ""
-- L["Worship Radius"] = ""
-- L["Wrack"] = ""
-- L["Wrack End"] = ""
-- L["Wrack Radius"] = ""
-- L["Wrack Start"] = ""
