local L = LibStub("AceLocale-3.0"):NewLocale("HudMap", "frFR")
if not L then return end

L["Bastion of Twilight"] = "Le bastion du Crépuscule"
-- L["Beth'tilac"] = ""
L["Blackwing Descent"] = "Descente de l'Aile noire"
L["Caustic Slime Range"] = "Portée de la Gelée caustique"
L["Chimaeron"] = "Chimaeron"
L["Cho'Gall"] = "Cho'gall"
-- L["Crystal Trap Duration"] = ""
-- L["Firelands"] = ""
-- L["Immolation Trap Duration"] = ""
-- L["Majordomo Staghelm"] = ""
L["Maloriak"] = "Maloriak"
L["Omnotron Defense System"] = "Système de défense Omnotron"
-- L["Shannox"] = ""
L["Sinestra"] = "Sinestra"
L["Twilight Ascendant Council"] = "Conseil d'ascendants"
L["Valiona and Theralion"] = "Valiona et Theralion"
L["Worship Radius"] = "Rayon de Vénération"
L["Wrack"] = "Calvaire"
L["Wrack End"] = "Fin Calvaire"
L["Wrack Radius"] = "Rayon de Calvaire"
L["Wrack Start"] = "Début Calvaire"
